[package]
name = "rust-system-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
druid = "0.8.3"
nvml-wrapper = "0.11.0"
sysinfo = "0.37.2"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"] }
im = "15.0"